import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AntdProvider from '@/components/providers/AntdProvider';
import IntlProviderWrapper from '@/components/providers/IntlProviderWrapper';
import AppContextProvider from '@/contexts';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppContextProvider>
          <IntlProviderWrapper>
            <AntdRegistry>
              <AntdProvider>{children}</AntdProvider>
            </AntdRegistry>
          </IntlProviderWrapper>
        </AppContextProvider>
      </body>
    </html>
  );
}
